apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: host-cluster
spec:
  generators:
  - list:
      elements:
      - cluster: host-cluster1
        url: https://10.204.118.216:6443
  template:
    metadata:
      name: '{{cluster}}'
    spec:
      project: platform
      source:
        repoURL: https://github.com/lanbingcloud/platform-cluster.git
        targetRevision: HEAD
        path: host-clusters/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: nautes
